### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by JDat** [jekil/UDPot#1]
error:
Unhandled Error
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/pi/.local/lib/python3.7/site-packages/twisted/names/dns.py", line 3151, in dataReceived
    self.controller.messageReceived(m, self)
  File "dns.py", line 66, in messageReceived
    entry["src_ip"] = address[0]
builtins.TypeError: 'NoneType' object is not subscriptable

os: Linux raspbian 4.19.97-v7+

**Comment by JDat** [comment]
Nevermind! I what TCP SYNC attack. For real UDP everything is working.

**Comment by jekil** [comment]
Don't worry, and thanks so much anyway!
